services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.9.3
    restart: unless-stopped
    ports:
      - 1080:1080
    volumes:
      - ./sing-box:/config/sing-box:ro
      # 或者使用 direct 模式, 不需要 frpc 客户端
      #- ./sing-box-direct:/config/sing-box:ro
    command: -c /config/sing-box/config.json run
  frpc:
    image: ghcr.io/fatedier/frpc:v0.59.0
    restart: unless-stopped
    volumes:
      - ./frpc:/config/frpc:ro
    command: -c /config/frpc/config.toml
networks:
  default:
    enable_ipv6: true # 启用 IPv6
