services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.9.3
    restart: unless-stopped
    ports:
      - 1080:1080
    volumes:
      - ./sing-box:/config/sing-box:ro
    command: -c /config/sing-box/config.json run
networks:
  default:
    enable_ipv6: true # 启用 IPv6
