services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.9.3
    restart: unless-stopped
    ports:
      - 12345:7001
    volumes:
      - ./sing-box:/config/sing-box:ro
    command: -c /config/sing-box/config.json -D /data/sing-box run
  frps:
    image: ghcr.io/fatedier/frps:v0.59.0
    restart: unless-stopped
    volumes:
      - ./frps:/config/frps:ro
    command: -c /config/frps/config.toml
volumes:
  data:
networks:
  default:
    enable_ipv6: true # 启用 IPv6
